version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=80
      - REACT_APP_API_URL=http://localhost:3001
      - DATABASE_URL=postgresql://immortal_user:immortal_secret_password@postgres:5432/immortal_path_db
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
