version: '3.8'

services:
  # База данных PostgreSQL 16
  postgres:
    image: postgres:16
    container_name: game_postgres
    environment:
      POSTGRES_DB: game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d game"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - game_network

  # Express API сервер
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: game_server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=game
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/game
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - game_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: game_app
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - game_network

networks:
  game_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local