// Типы действий
const ACTION_TYPES = {
  // Действия для групп и групповых активностей
  SET_GROUPS: 'SET_GROUPS',
  SET_CURRENT_GROUP: 'SET_CURRENT_GROUP',
  CREATE_GROUP: 'CREATE_GROUP',
  UPDATE_GROUP: 'UPDATE_GROUP',
  DELETE_GROUP: 'DELETE_GROUP',
  JOIN_GROUP: 'JOIN_GROUP',
  LEAVE_GROUP: 'LEAVE_GROUP',
  SET_GROUP_ACTIVITIES: 'SET_GROUP_ACTIVITIES',
  SET_CURRENT_ACTIVITY: 'SET_CURRENT_ACTIVITY',
  FETCH_USER_INVITATIONS: 'FETCH_USER_INVITATIONS',
  SET_USER_INVITATIONS: 'SET_USER_INVITATIONS',
  RESPOND_TO_INVITATION: 'RESPOND_TO_INVITATION',
  
  // Действия для экземпляров групповых активностей
  CREATE_ACTIVITY_INSTANCE: 'CREATE_ACTIVITY_INSTANCE',
  FETCH_GROUP_ACTIVITY_INSTANCES: 'FETCH_GROUP_ACTIVITY_INSTANCES',
  SET_GROUP_ACTIVITY_INSTANCES: 'SET_GROUP_ACTIVITY_INSTANCES',
  UPDATE_ACTIVITY_INSTANCE: 'UPDATE_ACTIVITY_INSTANCE',
  START_ACTIVITY: 'START_ACTIVITY',
  UPDATE_ACTIVITY_PROGRESS: 'UPDATE_ACTIVITY_PROGRESS',
  COMPLETE_ACTIVITY: 'COMPLETE_ACTIVITY',
  FAIL_ACTIVITY: 'FAIL_ACTIVITY',
  ABANDON_ACTIVITY: 'ABANDON_ACTIVITY',
  ADD_ACTIVITY_PARTICIPANT: 'ADD_ACTIVITY_PARTICIPANT',
  REMOVE_ACTIVITY_PARTICIPANT: 'REMOVE_ACTIVITY_PARTICIPANT',
  UPDATE_ACTIVITY_REWARDS: 'UPDATE_ACTIVITY_REWARDS',
  ADD_REWARDS: 'ADD_REWARDS',
  
  // Добавляем новый тип действия для инициализации погоды с прогнозом
  INITIALIZE_WEATHER: 'INITIALIZE_WEATHER',
  // Действие для установки данных пользователя (для решения проблем с авторизацией)
  SET_USER: 'SET_USER',
  UPDATE_PLAYER: 'UPDATE_PLAYER',
  UPDATE_PLAYER_STATS: 'UPDATE_PLAYER_STATS',
  UPDATE_CULTIVATION: 'UPDATE_CULTIVATION',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  EQUIP_ITEM: 'EQUIP_ITEM',
  UNEQUIP_ITEM: 'UNEQUIP_ITEM',
  UPDATE_CURRENCY: 'UPDATE_CURRENCY',
  UPDATE_LOCATION: 'UPDATE_LOCATION',
  UPDATE_TIME: 'UPDATE_TIME',
  UPDATE_WEATHER: 'UPDATE_WEATHER',
  ADD_EVENT: 'ADD_EVENT',
  REMOVE_EVENT: 'REMOVE_EVENT',
  CHANGE_SCREEN: 'CHANGE_SCREEN',
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SAVE_GAME: 'SAVE_GAME',
  LOAD_GAME: 'LOAD_GAME',
  ACCEPT_QUEST: 'ACCEPT_QUEST',
  COMPLETE_QUEST: 'COMPLETE_QUEST',
  UPDATE_QUEST_OBJECTIVE: 'UPDATE_QUEST_OBJECTIVE',
  CHECK_ACHIEVEMENTS: 'CHECK_ACHIEVEMENTS',
  COMPLETE_ACHIEVEMENT: 'COMPLETE_ACHIEVEMENT',
  LEARN_TECHNIQUE: 'LEARN_TECHNIQUE',
  UPGRADE_TECHNIQUE: 'UPGRADE_TECHNIQUE',
  USE_TECHNIQUE: 'USE_TECHNIQUE',
  START_COMBAT: 'START_COMBAT',
  END_COMBAT: 'END_COMBAT',
  UPDATE_COMBAT: 'UPDATE_COMBAT',
  UPDATE_COMBAT_STATE: 'UPDATE_COMBAT_STATE',
  ADD_COMBAT_LOG: 'ADD_COMBAT_LOG',
  ADD_STATUS_EFFECT: 'ADD_STATUS_EFFECT',
  UPDATE_STATUS_EFFECT: 'UPDATE_STATUS_EFFECT',
  REMOVE_STATUS_EFFECT: 'REMOVE_STATUS_EFFECT',
  SET_INITIALIZED: 'SET_INITIALIZED',
  SET_ERROR: 'SET_ERROR',
  
  // Действия для сект
  SET_SECT: 'SET_SECT',
  UPDATE_SECT: 'UPDATE_SECT',
  JOIN_SECT: 'JOIN_SECT',
  LEAVE_SECT: 'LEAVE_SECT',
  CONTRIBUTE_TO_SECT: 'CONTRIBUTE_TO_SECT',
  TRAIN_SECT_MEMBER: 'TRAIN_SECT_MEMBER',
  UPDATE_SECT_MEMBER: 'UPDATE_SECT_MEMBER',
  UPDATE_SECT_BENEFITS: 'UPDATE_SECT_BENEFITS',
  UPDATE_SECT_RANK: 'UPDATE_SECT_RANK',
  
  // Действия для духовных питомцев
  ADD_SPIRIT_PET: 'ADD_SPIRIT_PET',
  REMOVE_SPIRIT_PET: 'REMOVE_SPIRIT_PET',
  REMOVE_FLEEING_PET: 'REMOVE_FLEEING_PET',
  UPDATE_SPIRIT_PET: 'UPDATE_SPIRIT_PET',
  SET_ACTIVE_SPIRIT_PET: 'SET_ACTIVE_SPIRIT_PET',
  FEED_SPIRIT_PET: 'FEED_SPIRIT_PET',
  TRAIN_SPIRIT_PET: 'TRAIN_SPIRIT_PET',
  USE_PET_ABILITY: 'USE_PET_ABILITY',
  UPDATE_PETS_STATE: 'UPDATE_PETS_STATE',
  
  // Действия для рынка и торговли
  ADD_MARKET_ITEM: 'ADD_MARKET_ITEM',
  REMOVE_MARKET_ITEM: 'REMOVE_MARKET_ITEM',
  UPDATE_MARKET_ITEM: 'UPDATE_MARKET_ITEM',
  BUY_MARKET_ITEM: 'BUY_MARKET_ITEM',
  SELL_MARKET_ITEM: 'SELL_MARKET_ITEM',
  UPDATE_MERCHANT_REPUTATION: 'UPDATE_MERCHANT_REPUTATION',
  UPDATE_MARKET_STATE: 'UPDATE_MARKET_STATE',
  
  // Действия для кэширования врагов
  CACHE_GENERATED_ENEMY: 'CACHE_GENERATED_ENEMY',
  
  // Действия для экипировки
  APPLY_EQUIPMENT_BONUSES: 'APPLY_EQUIPMENT_BONUSES',
  
  // Действия для отношений с персонажами
  UPDATE_RELATIONSHIP: 'UPDATE_RELATIONSHIP',
  
  // Действие для исправления техник
  REPAIR_TECHNIQUES: 'REPAIR_TECHNIQUES',
  
  // Действие для сохранения истории боев в состоянии игрока
  ADD_COMBAT_HISTORY: 'ADD_COMBAT_HISTORY',
  
  // Действие для нормализации данных сект
  NORMALIZE_SECT_DATA: 'NORMALIZE_SECT_DATA',
  
  // Действие для нормализации эффектов
  NORMALIZE_EFFECTS: 'NORMALIZE_EFFECTS',
  
  // Действия для синхронизации отношений между сектой и социальными отношениями
  SYNC_SECT_TO_SOCIAL: 'SYNC_SECT_TO_SOCIAL',
  SYNC_SOCIAL_TO_SECT: 'SYNC_SOCIAL_TO_SECT',
  UPDATE_SECT_LOYALTY: 'UPDATE_SECT_LOYALTY',
  UPDATE_SOCIAL_RELATIONSHIPS: 'UPDATE_SOCIAL_RELATIONSHIPS',
  UPDATE_SECT_DATA: 'UPDATE_SECT_DATA',
  
  // Действие для одновременного обновления отношений и лояльности
  UPDATE_RELATIONSHIP_AND_LOYALTY: 'UPDATE_RELATIONSHIP_AND_LOYALTY',
  
  // Действия для погоды и времени
  WEATHER_INIT: 'WEATHER_INIT',
  WEATHER_CHANGE: 'WEATHER_CHANGE',
  SEASON_CHANGE: 'SEASON_CHANGE',
  TIME_PERIOD_CHANGE: 'TIME_PERIOD_CHANGE',
  APPLY_WEATHER_EFFECTS: 'APPLY_WEATHER_EFFECTS',
  
  // Действия для API эффектов
  WEATHER_EFFECTS_UPDATE: 'WEATHER_EFFECTS_UPDATE',
  TECHNIQUE_EFFECTS_UPDATE: 'TECHNIQUE_EFFECTS_UPDATE',
  SECT_EFFECTS_UPDATE: 'SECT_EFFECTS_UPDATE',
  EQUIPMENT_EFFECTS_UPDATE: 'EQUIPMENT_EFFECTS_UPDATE',
  PET_EFFECTS_UPDATE: 'PET_EFFECTS_UPDATE',
  STATUS_EFFECTS_UPDATE: 'STATUS_EFFECTS_UPDATE',
  ALL_EFFECTS_UPDATE: 'ALL_EFFECTS_UPDATE',
  
  // Действия для API инвентаря
  UPDATE_INVENTORY: 'UPDATE_INVENTORY',
  UPDATE_ITEM: 'UPDATE_ITEM',
  ADD_ITEMS_BATCH: 'ADD_ITEMS_BATCH',
  FILTER_INVENTORY: 'FILTER_INVENTORY',
  CLEAR_INVENTORY: 'CLEAR_INVENTORY',
  
  // Действия для обогащения предметов данными из БД
  ENRICH_ITEM_REQUEST: 'ENRICH_ITEM_REQUEST',
  ENRICH_ITEM_SUCCESS: 'ENRICH_ITEM_SUCCESS',
  ENRICH_ITEM_FAILURE: 'ENRICH_ITEM_FAILURE',
  
  // Действие для полного сброса состояния (для решения проблемы с валютой при новой регистрации)
  RESET_STATE: 'RESET_STATE',
  UPDATE_PLAYER_BENEFITS: 'UPDATE_PLAYER_BENEFITS',
  
  // Действия для характеристик персонажа
  LOAD_CHARACTER_STATS: 'LOAD_CHARACTER_STATS',
  UPDATE_CHARACTER_STATS: 'UPDATE_CHARACTER_STATS',
  
  // Действия для аватарки персонажа
  UPLOAD_AVATAR_REQUEST: 'UPLOAD_AVATAR_REQUEST',
  UPLOAD_AVATAR_SUCCESS: 'UPLOAD_AVATAR_SUCCESS',
  UPLOAD_AVATAR_FAILURE: 'UPLOAD_AVATAR_FAILURE',
  SET_AVATAR: 'SET_AVATAR',
  CLEAR_AVATAR: 'CLEAR_AVATAR'
};

export default ACTION_TYPES;
